name: cog_x_r
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.7
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.2
  flutter_native_splash: ^2.2.8
  get: 4.6.5
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
